version: '2.1'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - HOSTNAME=plex
      - TZ=<time-zone>
      - PLEX_CLAIM=<claim>
    networks:
      - default
    volumes:
      - ~/Fuentes/movies/media-server/config/plex/config:/config
      - ~/Fuentes/movies/media-server/config/plex/transcode:/transcode
      - ~/Fuentes/movies/media-server/data:/data
  transmission:
    container_name: transmission
    image: linuxserver/transmission
    restart: unless-stopped
    networks:
      - default
    ports:
      - 9091:9091 
      - 51413:51413 
    environment:
      - HOSTNAME=transmission
      - PGID=1000 
      - PUID=1000
      - TZ=America/La_Paz
    volumes:
      - ~/Fuentes/movies/media-server/config/transmission/config:/config
      - ~/Fuentes/movies/media-server/downloads:/downloads
      - ~/Fuentes/movies/media-server/watch:/watch
  flexget:
    container_name: flexget
    image: cpoppema/docker-flexget
    restart: unless-stopped
    networks:
      - default
    extra_hosts:
      - "outside:<local-ip>"
    links:
      - transmission
    ports:
      - "5050:5050"
    environment:
      - HOSTNAME=flexget
      - PGID=1000 
      - PUID=1000 
      - WEB_PASSWD=yourhorriblesecret
      - TORRENT_PLUGIN=transmission 
      - FLEXGET_LOG_LEVEL=debug 
    volumes:
      - ~/Fuentes/movies/media-server/config/flexget/config:/config
      - ~/Fuentes/movies/media-server/downloads:/downloads
      - ~/Fuentes/movies/media-server/data:/data
