version: '2.1'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    hostname: plex
    restart: unless-stopped
    network_mode: host
    environment:
      - PGID=994
      - PUID=994
      - HOSTNAME=plex
      - TZ=America/La_Paz
      - PLEX_CLAIM=<CLAIM>
      - ADVERTISE_IP=http://192.168.1.100:32400/
    volumes:
      - /media-server/config/plex/config:/config
      - /media-server/config/plex/transcode:/transcode
      - /media:/data
      - /run
  transmission:
    container_name: transmission
    image: linuxserver/transmission
    restart: unless-stopped
    networks:
      - default
    ports:
      - 9091:9091 
      - 51413:51413 
    environment:
      - HOSTNAME=transmission
      - PGID=0
      - PUID=0
      - TZ=America/La_Paz
    volumes:
      - /media-server/config/transmission/config:/config
      - /downloads:/downloads
      - /watch:/watch
  flexget:
    container_name: flexget
    image: cpoppema/docker-flexget
    restart: unless-stopped
    networks:
      - default
    extra_hosts:
      - "outside:192.168.1.100"
    #links:
    #  - transmission
    ports:
      - "5050:5050"
    environment:
      - HOSTNAME=flexget
      - PGID=0 
      - PUID=0
      - WEB_PASSWD=yourhorriblesecret
      - TORRENT_PLUGIN=transmission 
      - FLEXGET_LOG_LEVEL=debug 
    volumes:
      - /media-server/config/flexget/config:/config
      - /downloads:/downloads
      - /media:/data

